service: lumo-example

custom:
  cljsCompiler: lumo

provider:
  name: aws
  runtime: nodejs4.3

functions:
  example:
    cljs: lumo-example.core/example

package:
  exclude:
    - node_modules/.yarn*

plugins:
  - serverless-cljs-plugin
